name: nlp
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - flake8
  - mypy
  - pytest
  - sphinx
  - jupyter
  - pandas
  - plotly
  - numpy
  - pytorch
  - transformers
  - accelerate
  - nltk
  - bert_score
  - pandas-stubs
